### ISSUE TITLE
Iframe loads bare jquery.wymeditor.js, which doesn't break the cache

### ISSUE THREAD

**Issue by winhamwr** [wymeditor/wymeditor#667]
The popup windows get cached code, which means new WYMeditor releases look buggy to end users. 

* By default, use the WYMeditor.VERSION as a GET parameter (e.g. `foo/jquery.browser.js?v=1.0.0rc1`)
* Add a configuration parameter to let the user manually modify this

**Comment by mightyiam** [comment]
Cached code? Really? It didn't happen to me... Perhaps during development the caching was prevented or I just didn't notice it?

How does it look?

Regarding your solution, I don't understand it. What Are you suggesting? I think a better understanding of the issue is required. Can you please explain more deeply?

I don't quite get how it is possible that the popup windows get cached code. They don't perform any requests. They are constructed using JS from the parent window, completely.

Where, in that process, do they get cached code? Which code?

**Comment by winhamwr** [comment]
The iframe loads `jquery.wymeditor.js`. If the user had previously loaded say version 1.0.0b8 and the version on the server is 1.0.0rc1, the browser says "I already have jquery.wymeditor.js in my cache" and doesn't make the request. This causes errors.

If the iframe appended the version number to the path in the `<script>` tag, the browser would know to request the file from the server again. Basically, something like [this](http://webassets.readthedocs.org/en/latest/expiring.html#expire-using-a-querystring).

**Comment by winhamwr** [comment]
My diagnosis was wrong. The new dialog system doesn't load `jquery.wymeditor.js` like we used to. I need to dig a little deeper to figure out why PolicyStat's static-asset cache busting didn't work with the WYMeditor update we did last week.

**Comment by winhamwr** [comment]
Confirmed that this is fixed on master. We ran into it at PolicyStat because we're running 3f9e9c9 on [this branch](https://github.com/wymeditor/wymeditor/compare/patch-nested-table-fix). It's a patched version of rc.1 with a couple of the large bug fixes backported from master (#666 and b5c0581). It will be very nice to push out a new RC, soon. Been a long time since we've had a release. Undo/redo, here we come!
